app/Http/routes.php
<?php

Route::get('/', 'PagesController@index');

Route::get('home', [
	'as' => 'home',
	'uses' => 'PagesController@index'

]);

Route::get('about', [
			'as' => 'about',
			'uses' => 'PagesController@about'
]);

Route::get('service/trade-fair-exhibition', [
			'as' => 'service.trade.index',
			'uses'=> 'ServicesController@TradeIndex'
]);

Route::post('service/register', [
			'as' => 'service.register',
			'uses' => 'ServicesController@Register'
]);

Route::get('service/trade-fair-exhibition/{post}', [
			'as' => 'service.trade.show',
			'uses' => 'ServicesController@TradeShow'
]);

Route::get('service', [
		'as' 	=> 'service.index',
		'uses' 	=> 'ServicesController@ServiceIndex'
]);

Route::post('service', [
			'as' => 'service.store',
			'uses' => 'ServicesController@ServiceStore'
]);

Route::get('service/{service}', [
			'as' => 'service.service',
			'uses' => 'ServicesController@ServiceService'
]);

Route::get('service/{service}/{category}', [
		'as' => 'service.category',
		'uses' => 'ServicesController@ServiceCategory'
]);

Route::get('service/{service}/{category}/{subcategory}', [
		'as' => 'service.subcategory',
		'uses' => 'ServicesController@ServiceSubcategory'
]);

Route::get('service/{service}/{category}/{subcategory}/{post}', [
		'as' => 'service.post',
		'uses' => 'ServicesController@ServiceShow'
]);

/*Authentication*/

Route::group(['middleware' => 'auth'], function() {

	// Admin

	Route::get('admin', 'AdminController@SupportIndex');

	Route::get('admin/support', [
		'as' 	=> 'admin.support',
		'uses' 	=> 'AdminController@SupportIndex'
	]);

	Route::get('admin/support/show={id}',[
		'as' 	=> 'admin.support.show',
		'uses' 	=> 'AdminController@SupportShow'
	]);

	Route::get('admin/register', [
		'as'   => 'admin.register.index',
		'uses' => 'AdminController@RegisterIndex'
	]);

	Route::get('admin/register/show={id}', [
		'as'   => 'admin.register.show',
		'uses' => 'AdminController@RegisterShow'
	]);

	Route::get('admin/partner', [
		'as'   => 'admin.partner.index',
		'uses' => 'AdminController@PartnerIndex'
	]);

	Route::get('admin/partner/edit={id}', [
		'as'   => 'admin.partner.edit',
		'uses' => 'AdminController@PartnerEdit'
	]);

	Route::get('admin/partner/create', [
		'as'   => 'admin.partner.create',
		'uses' => 'AdminController@PartnerCreate'
	]);

	Route::post('admin/partner', [
		'as'   => 'admin.partner.store',
		'uses' => 'AdminController@PartnerStore'
	]);

	Route::post('admin/partner/destroy', [
		'as'   => 'admin.partner.destroy',
		'uses' => 'AdminController@PartnerDestroy'
	]);

	/*------------Trade Fair Exhibition------------*/

	Route::get('admin/service/tfe', [
		'as'   => 'admin.service.tfe',
		'uses' => 'AdminController@ServiceTfe'
	]);

	Route::post('admin/service/tfe', [
		'as'   => 'admin.service.tfe.store',
		'uses' => 'AdminController@ServiceTfeStore'
	]);

	Route::get('admin/service/tfe/create', [
		'as'   => 'admin.service.tfe.create',
		'uses' => 'AdminController@ServiceTfeCreate'
	]);

	Route::post('admin/service/update={id}', [
		'as'   => 'admin.service.tfe.update',
		'uses' => 'AdminController@ServiceTfeUpdate'
	]);

	Route::get('admin/service/tfe/edit={id}', [
		'as'   => 'admin.service.tfe.edit',
		'uses' => 'AdminController@ServiceTfeEdit'
	]);

	Route::post('admin/service/tfe/destroy', [
		'as'   => 'admin.service.tfe.destroy',
		'uses' => 'AdminController@ServiceTfeDestroy'
	]);

	/*-----------------------------------------------------*/

	/*---------------------Service-------------------------*/

	Route::get('admin/service/index={id}', [
		'as'   => 'admin.service.index',
		'uses' => 'AdminController@ServiceIndex'
	]);

	Route::get('admin/service/category={id}', [
		'as'   => 'admin.service.category.index',
		'uses' => 'AdminController@ServiceCategoryIndex'
	]);

	Route::get('admin/service/category/create={id}',[
		'as'   => 'admin.service.category.create',
		'uses' => 'AdminController@ServiceCategoryCreate'
	]);

	Route::get('admin/service/category/edit={id}&c={c_id}', [
		'as'   => 'admin.service.category.edit',
		'uses' => 'AdminController@ServiceCategoryEdit'
	]);

	Route::post('admin/service/category/store', [
		'as'   => 'admin.service.category.store',
		'uses' => 'AdminController@ServiceCategoryStore'
	]);

	Route::post('admin/service/category/destroy', [
		'as'   => 'admin.service.category.destroy',
		'uses' => 'AdminController@ServiceCategoryDestroy'
	]);

	Route::get('admin/service/subcategory/create={id}', [
		'as'   => 'admin.service.subcategory.create',
		'uses' => 'AdminController@ServiceSubcategoryCreate'
	]);

	Route::get('admin/service/subcategory/edit={id}&s={s_id}', [
		'as'   => 'admin.service.subcategory.edit',
		'uses' => 'AdminController@ServiceSubcategoryEdit'
	]);

	Route::post('admin/service/subcategory/store', [
		'as'   => 'admin.service.subcategory.store',
		'uses' => 'AdminController@ServiceSubcategoryStore'
	]);

	Route::get('admin/service/post={id}&view={view}', [
		'as'   => 'admin.service.post.index',
		'uses' => 'AdminController@ServicePostIndex'
	]);

	Route::get('admin/service/post/create={id}', [
		'as'   => 'admin.service.post.create',
		'uses' => 'AdminController@ServicePostCreate'
	]);

	Route::get('admin/service/post/edit={id}&service={s_id}', [
		'as'   => 'admin.service.post.edit',
		'uses' => 'AdminController@ServicePostEdit'
	]);

	Route::post('admin/service/post/store', [
		'as'   => 'admin.service.post.store',
		'uses' => 'AdminController@ServicePostStore'
	]);

	Route::post('admin/service/post/destroy', [
		'as'   => 'admin.service.post.destroy',
		'uses' => 'AdminController@ServicePostDestroy'
	]);

	/*-----------------------------------------------------*/

	// Upload
	Route::get('upload', [
		'as' 	=> 'upload.index',
		'uses'	=> 'ServiceFilemanager@Index'
	]);

	Route::post('upload/store', [
		'as'	=> 'upload.store',
		'uses'	=> 'ServiceFilemanager@Store'
	]);

	Route::post('upload/files', [
		'as'   => 'upload.files',
		'uses' => 'ServiceFilemanager@ListFile'
	]);

	Route::post('upload/destroy', [
		'as'	=> 'upload.destroy',
		'uses'	=> 'ServiceFilemanager@Destroy'
	]);

});

Route::get('admin/login', [
	'as'   => 'admin.login',
	'uses' => 'Auth\AuthController@getLogin'
]);

Route::post('admin/login', [
	'as'   => 'admin.login.post',
	'uses' => 'Auth\AuthController@postLogin'
]);

Route::get('admin/logout', [
	'as'   => 'admin.logout',
	'uses' => 'Auth\AuthController@getLogout' 
]);

app/Register.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon as Carbon;

class Register extends Model
{
    
	protected $fillable = [
		'category',
		'post',
		'name',
		'email',
		'phone',
		'address',
		'company',
		'read'
	];

	protected $guarded = [];

	public function getCreatedAtAttribute($value)
	{

		return Carbon::parse($value)->format('d-m-Y');

	}

}

resources/views/admin/register/index.blade.php
@extends('admin.layouts.master')

@section('head.title')
	Thông tin khách hàng đăng ký dịch vụ
@endsection

@section('content')

	<ol class="breadcrumb">
		<li><a href="#">Dasboard</a></li>
		<li><a href="{{ route('admin.register.index') }}">Đăng ký</a></li>
	</ol>

	<div class="panel panel-primary">
		<div class="panel-heading">
			<h4>Thông tin khách hàng đăng ký dịch vụ</h4>
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Tên người đăng ký</th>
					<th>Loại</th>
					<th>Ngày yêu cầu</th>
					<th>Trạng thái</th>
					<th>Chức năng</th>
				</tr>
			</thead>
			<tbody>
			@foreach($posts as $post)
				<tr>
					<td>{{ $post['name'] }}</td>
					<td>{{ $post['category'] }}</td>
					<td>{{ $post->created_at }}</td>
					<td>
					@if($post['read'])
						<p class="bg-success">Đã đọc
					@else
						<p class="bg-danger">Chưa đọc
					@endif
						</p>
					</td>
					<td>
						<button class="btn btn-info" onclick="window.location.assign('{{ route('admin.register.show', $post['id']) }}')">Đọc</button>
						<button class="btn btn-danger">Xóa</button>
					</td>
				</tr>
			@endforeach
			</tbody>
		</table>
		<div class="panel-footer text-center">
			{!! $posts->links() !!}
		</div>
	</div>

@endsection

resources/views/admin/register/show.blade.php
@extends('admin.layouts.master')

@section('head.title')
	{{ $post['category'] }}
@endsection

@section('content')

	<ol class="breadcrumb">
		<li><a href="#">Dasboard</a></li>
		<li><a href="{{ route('admin.register.index') }}">Đăng ký</a></li>
	</ol>

	<div class="panel panel-primary">
		<div class="panel-heading">
			<h4>Yêu cầu - Khách - {{ $post['name'] }}</h4>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-2"><code>Họ và tên khách:</code></div>
				<div class="col-md-4">{{ $post['name'] }}</div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Loại yêu cầu:</code></div>
				<div class="col-md-4">{{ $post['category'] }}</div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Liên kết gian hàng:</code></div>
				<div class="col-md-4"><a href="{{ route('service.trade.show' ,$post['post']) }}" target="_blank">{{ route('service.trade.show' ,$post['post']) }}</a></div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Email:</code></div>
				<div class="col-md-4">{{ $post['email'] }}</div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Điện thoại:</code></div>
				<div class="col-md-4">{{ $post['phone'] }}</div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Địa chỉ:</code></div>
				<div class="col-md-4">{{ $post['address'] }}</div>
			</div>
			<div class="row">
				<div class="col-md-2"><code>Công ty:</code></div>
				<div class="col-md-4">{{ $post['company'] }}</div>
			</div>
		</div>
		<div class="panel-footer"></div>
	</div>

@endsection